name: cli_example
description: DartSV CLI Demo Application
version: 0.3.0
homepage: https://github.com/twostack/cli-example
author: Stephan M. February <stephan@werkswinkel.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  hex: 0.2.0
  collection: ^1.14.11
  sprintf: ^6.0.0
  http: ^0.13.3
  dartsv: ^1.0.0
  bip39: ^1.0.3


dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
